---
abstract: 'The great new Net::MeasuringBandwidth!'
author:
  - 'Ovidiu N.Tatar <ovn.tatar@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-MeasuringBandwidth
provides:
  Net::MeasuringBandwidth:
    file: lib/Net/MeasuringBandwidth.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
